//! Rust structs mirroring the SQLite schema (see docs/schema.md §3).
//!
//! Integer columns use `i64` because SQLite stores every INTEGER as a 64-bit
//! signed value; sqlx's `FromRow` rejects `i32` unless you convert explicitly.

use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Project {
    pub id: String,
    pub name: String,
    pub repo_path: String,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Execution {
    pub id: String,
    pub project_id: String,
    pub skill_name: String,
    pub status: String,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub total_steps: i64,
    pub completed_steps: i64,
    pub created_at: String,
    /// Chat thread that triggered this run, if any. NULL for executions
    /// started outside the chat (manual, future cron, programmatic
    /// triggers). Populated by `execute_skill` when the SkillExecutePanel
    /// passes the route's conversationId.
    pub conversation_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ExecutionStep {
    pub id: String,
    pub execution_id: String,
    pub step_id: String,
    pub step_order: i64,
    pub tool: String,
    pub status: String,
    pub input: String,
    pub output: Option<String>,
    pub error: Option<String>,
    pub retries: i64,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub duration_ms: Option<i64>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ChatMessage {
    pub id: String,
    pub execution_id: Option<String>,
    pub conversation_id: Option<String>,
    pub role: String,
    pub content: String,
    pub created_at: String,
    /// Discriminator for the chat renderer. `'text'` (default) is a
    /// regular bubble; `'execution-status'` is the inline ⏳/✅/❌
    /// progress message rendered with the smaller, sutil style.
    /// Renamed at the wire boundary because `type` is a TS reserved
    /// keyword for some payloads — keeping the JSON key as `type`
    /// matches the existing frontend ChatMessageType union.
    #[serde(rename = "type", default = "default_message_kind")]
    pub kind: String,
    /// Extended-thinking text from models that expose reasoning. Stored
    /// alongside the message for replay; omitted from regular text turns.
    pub thinking: Option<String>,
    /// One-line summary of the thinking block — used by the UI's collapsed
    /// accordion header. Generated by the chat router from the first chars
    /// of the first non-empty line.
    pub thinking_summary: Option<String>,
}

fn default_message_kind() -> String {
    "text".to_string()
}

impl Default for ChatMessage {
    fn default() -> Self {
        Self {
            id: String::new(),
            execution_id: None,
            conversation_id: None,
            role: String::new(),
            content: String::new(),
            created_at: String::new(),
            kind: default_message_kind(),
            thinking: None,
            thinking_summary: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Conversation {
    pub id: String,
    pub title: String,
    pub created_at: String,
    pub updated_at: String,
}

/// Generic single-row-per-key store for UI state that survives between
/// sessions (active project, active model, etc). Backed by the `app_state`
/// table — see migration 003.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AppState {
    pub key: String,
    pub value: String,
    pub updated_at: String,
}

/// Single uploaded markdown file in the knowledge base. Full row is
/// returned by `get_knowledge_file(id)` and bulk-fetched when the
/// summarizer regenerates the digest. Other surfaces (sidebar list,
/// settings) prefer `KnowledgeFileMeta` to keep payloads small.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeFile {
    pub id: String,
    pub filename: String,
    pub content: String,
    pub uploaded_at: String,
}

/// Lightweight projection of `KnowledgeFile` for list views — drops the
/// `content` column (can run into hundreds of KB per row). Maps to
/// `SELECT id, filename, uploaded_at FROM knowledge_files ...`.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeFileMeta {
    pub id: String,
    pub filename: String,
    pub uploaded_at: String,
}

/// AI-generated digest of all uploaded knowledge files, stored as a
/// singleton row (id = 'singleton'). UPSERT-ed every time the summarizer
/// runs. `source_count` records how many files contributed to the
/// current text — useful for stale-detection in the UI.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeSummary {
    pub id: String,
    pub summary: String,
    pub generated_at: String,
    pub source_count: i64,
}
