//! Rust structs mirroring the SQLite schema (see docs/schema.md §3).
//!
//! Integer columns use `i64` because SQLite stores every INTEGER as a 64-bit
//! signed value; sqlx's `FromRow` rejects `i32` unless you convert explicitly.

use serde::{Deserialize, Serialize};
use sqlx::FromRow;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Project {
    pub id: String,
    pub name: String,
    pub repo_path: String,
    pub created_at: String,
    pub updated_at: String,
}

/// User-facing alias for [`Project`]. The product is migrating its
/// surface vocabulary from "project" to "caminho" (Portuguese for
/// "path") since users mostly think of these as folder bookmarks
/// rather than software projects. Schema + queries stay on `Project`;
/// `Caminho` is just a rename at the API boundary so handlers in
/// `commands/caminhos.rs` can read naturally without duplicating the
/// row struct.
pub type Caminho = Project;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Execution {
    pub id: String,
    pub project_id: String,
    pub skill_name: String,
    pub status: String,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub total_steps: i64,
    pub completed_steps: i64,
    pub created_at: String,
    /// Chat thread that triggered this run, if any. NULL for executions
    /// started outside the chat (manual, future cron, programmatic
    /// triggers). Populated by `execute_skill` when the SkillExecutePanel
    /// passes the route's conversationId.
    pub conversation_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ExecutionStep {
    pub id: String,
    pub execution_id: String,
    pub step_id: String,
    pub step_order: i64,
    pub tool: String,
    pub status: String,
    pub input: String,
    pub output: Option<String>,
    pub error: Option<String>,
    pub retries: i64,
    pub started_at: Option<String>,
    pub finished_at: Option<String>,
    pub duration_ms: Option<i64>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ChatMessage {
    pub id: String,
    pub execution_id: Option<String>,
    pub conversation_id: Option<String>,
    pub role: String,
    pub content: String,
    pub created_at: String,
    /// Discriminator for the chat renderer. `'text'` (default) is a
    /// regular bubble; `'execution-status'` is the inline ⏳/✅/❌
    /// progress message rendered with the smaller, sutil style.
    /// Renamed at the wire boundary because `type` is a TS reserved
    /// keyword for some payloads — keeping the JSON key as `type`
    /// matches the existing frontend ChatMessageType union.
    #[serde(rename = "type", default = "default_message_kind")]
    pub kind: String,
    /// Extended-thinking text from models that expose reasoning. Stored
    /// alongside the message for replay; omitted from regular text turns.
    pub thinking: Option<String>,
    /// One-line summary of the thinking block — used by the UI's collapsed
    /// accordion header. Generated by the chat router from the first chars
    /// of the first non-empty line.
    pub thinking_summary: Option<String>,
}

fn default_message_kind() -> String {
    "text".to_string()
}

impl Default for ChatMessage {
    fn default() -> Self {
        Self {
            id: String::new(),
            execution_id: None,
            conversation_id: None,
            role: String::new(),
            content: String::new(),
            created_at: String::new(),
            kind: default_message_kind(),
            thinking: None,
            thinking_summary: None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Conversation {
    pub id: String,
    pub title: String,
    pub created_at: String,
    pub updated_at: String,
    /// `@<name>` da última integration invocada nesta thread. Quando
    /// `Some`, o chat injeta a spec mesmo sem o usuário re-prefixar
    /// turnos seguintes — sticky até a thread ser arquivada/limpa.
    /// NULL na criação; preenchido por send_chat_message.
    #[serde(default)]
    pub active_integration: Option<String>,
}

/// Generic single-row-per-key store for UI state that survives between
/// sessions (active project, active model, etc). Backed by the `app_state`
/// table — see migration 003.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct AppState {
    pub key: String,
    pub value: String,
    pub updated_at: String,
}

/// Single uploaded markdown file in the knowledge base. Full row is
/// returned by `get_knowledge_file(id)` and bulk-fetched when the
/// summarizer regenerates the digest. Other surfaces (sidebar list,
/// settings) prefer `KnowledgeFileMeta` to keep payloads small.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeFile {
    pub id: String,
    pub filename: String,
    pub content: String,
    pub uploaded_at: String,
}

/// Lightweight projection of `KnowledgeFile` for list views — drops the
/// `content` column (can run into hundreds of KB per row). Maps to
/// `SELECT id, filename, uploaded_at FROM knowledge_files ...`.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeFileMeta {
    pub id: String,
    pub filename: String,
    pub uploaded_at: String,
}

/// AI-generated digest of all uploaded knowledge files, stored as a
/// singleton row (id = 'singleton'). UPSERT-ed every time the summarizer
/// runs. `source_count` records how many files contributed to the
/// current text — useful for stale-detection in the UI.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct KnowledgeSummary {
    pub id: String,
    pub summary: String,
    pub generated_at: String,
    pub source_count: i64,
}

/// One row per @-mention the user can invoke in chat. Two flavors live
/// in the same table (discriminated by `type_`):
///   - `"native"`     — shipped with the app (terminal, code). `channel`
///                      points at the executor backend (bash / claude-code
///                      / api).
///   - `"connector"`  — third-party integration. `channel` is `None`;
///                      auth + endpoints live inside the `config` JSON.
///
/// `doc_ai` is the snippet injected into the system prompt when the
/// capability is mentioned, so the model knows what it does and the
/// rules to follow. `doc_user` is the picker copy for humans.
///
/// Field rename: SQLite reserves no keyword named `type`, but Rust does
/// — `type_` is the field, serde's `rename = "type"` keeps the JSON
/// wire shape and the FromRow column lookup aligned with the
/// `capabilities.type` column.
/// Relational mirror of a skill v2 package em `~/.genesis/skills/<name>/`.
/// SKILL.md em disco é a source-of-truth do conteúdo; esta linha é
/// só metadata pra listagem rápida (autor / versão / contagem de
/// arquivos / flags pra UI mostrar badge "tem assets" / "tem refs").
///
/// `has_assets`/`has_references` são `i64` (0/1) porque SQLite
/// armazena INTEGER como 64-bit; a CHECK constraint da migration
/// pina pra binário no write.
///
/// `author` é nullable — frontmatter v1 nem sempre traz e a UI
/// mostra "—" quando ausente.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct SkillRow {
    pub id: String,
    pub name: String,
    pub version: String,
    pub author: Option<String>,
    pub has_references: i64,
    pub has_assets: i64,
    /// Migration 010 (A2). DEFAULT 0 + CHECK(0|1).
    pub has_scripts: i64,
    pub files_count: i64,
    pub created_at: String,
    pub updated_at: String,
}

/// Relational mirror of an `[integrations.<name>]` entry in
/// ~/.genesis/config.toml. Stored separately so the picker / list views
/// can run as fast SQL queries — but the **api_key never lands here**.
/// Read keys via `integrations::get_api_key(name)` from the TOML.
///
/// `auth_type` holds only the discriminator (`'bearer' | 'header' |
/// 'query'`); the full payload (header_name, param_name) lives TOML-side
/// to avoid a schema migration every time the user renames a header.
///
/// `enabled` is `i64` because SQLite stores INTEGER as 64-bit; the
/// CHECK constraint pins it to 0/1 at write time.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct IntegrationRow {
    pub id: String,
    pub name: String,
    pub display_name: String,
    pub base_url: String,
    pub auth_type: String,
    pub spec_file: String,
    pub enabled: i64,
    pub last_used_at: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct Capability {
    pub id: String,
    pub name: String,
    pub display_name: String,
    pub description: String,
    #[serde(rename = "type")]
    #[sqlx(rename = "type")]
    pub type_: String,
    pub channel: Option<String>,
    pub config: String,
    pub doc_ai: String,
    pub doc_user: String,
    pub enabled: i64,
    pub created_at: String,
    pub updated_at: String,
}
